### ISSUE TITLE
Primary and secondary stresses

### ISSUE THREAD

**Issue by phlnx** [wwesantos/arpabet-to-ipa#1]
Hi, thank you for this class, I am putting it to use and it works great.

I noticed the primary and secondary stresses are not provided in the IPA rendition, but arpabet specifies them through the [final vowel](https://en.wikipedia.org/wiki/Arpabet#Stress) on certain vocalic phonemes.

I cloned the project and added the stress marks where needed (a trivial change). I am rather new to Github and I don't know how to go from here. I would appreciate your help in suggesting how to proceed.

I am attaching the modified file.

Thank you for your attention!

[App.zip](https://github.com/wwesantos/arpabet-to-ipa/files/587495/App.zip)

**Comment by phlnx** [comment]
I just realized it's not that simple and that the stresses should go in front of the syllables, not in front of the vowels. I will work further on this.

**Comment by TheXenocide** [comment]
@phlnx did you ever get those IPA stresses implemented? Just curious, really, but would like to see it if possible.

**Comment by phlnx** [comment]
Hello TheXenocide, I [forked the project](https://github.com/phlnx/arpabet-to-ipa) and I managed to implement the stresses, although it's kind of a patch and it might be wrong in certain cases, I couldn't find any mistake so far. You're free to clone and improve if you feel like that. All the best

**Comment by TheXenocide** [comment]
@phlnx Awesome! Thanks for the expedient reply. I'm considering mapping between the two in a fun little side project I'm working on and there's other things I need to implement first, but I'll definitely take a look.
