### ISSUE TITLE
"RH" was not found

### ISSUE THREAD

**Issue by paraboloidas** [wwesantos/arpabet-to-ipa#2]
Hi, 
I am facing with this error:
_Fatal error: Uncaught InvalidArgumentException: Arpabet-to-IPA::phoneme "RH" was not found in_ 
It's obvious that phoneme "RH" was not found. Maybe there is some issue for it?

Thanks.

**Comment by wwesantos** [comment]
Hello. "RH" is not part of the list of phonemes for Arpabet.

https://en.m.wikipedia.org/wiki/ARPABET

If you need, you can define your own corversion table by calling setConvertionTable.
